CREATE TABLE IF NOT EXISTS `glossaries` (
    `catalog`     VARCHAR(25)
                  NOT NULL
                  COMMENT '分类目录',
    `iota`        TINYINT UNSIGNED
                  NOT NULL
                  COMMENT '值枚举',
    `name`        VARCHAR(50)
                  NOT NULL
                  COMMENT '值名称',
    `description` VARCHAR(150)
                  NOT NULL
                  COMMENT '值描述',
    `version`     INT UNSIGNED
                  NOT NULL
                  COMMENT '版本',
    `update_at`   INT UNSIGNED
                  COMMENT '修改时间',
    `create_at`   INT UNSIGNED
                  NOT NULL
                  COMMENT '创建时间',
    PRIMARY KEY `pk_glossaries` (`catalog`, `iota`)
)
ENGINE = InnoDB
COMMENT = '字典表'
DEFAULT CHARSET = utf8mb4
DEFAULT COLLATE = utf8mb4_general_ci;

INSERT INTO mm_glossaries(catalog, iota, name, description, version, create_at) VALUES 
('data-types',  1, 'bit',        'TypeBit',        1, UNIX_TIMESTAMP()),
('data-types',  2, 'boolean',    'TypeBoolean',    1, UNIX_TIMESTAMP()),
('data-types',  3, 'tinyint',    'TypeTiny',       1, UNIX_TIMESTAMP()),
('data-types',  4, 'smallint',   'TypeShort',      1, UNIX_TIMESTAMP()),
('data-types',  5, 'mediumint',  'TypeInt24',      1, UNIX_TIMESTAMP()),
('data-types',  6, 'int',        'TypeInt',        1, UNIX_TIMESTAMP()),
('data-types',  7, 'bigint',     'TypeBigInt',     1, UNIX_TIMESTAMP()),
('data-types',  8, 'decimal',    'TypeDecimal',    1, UNIX_TIMESTAMP()),
('data-types',  9, 'float',      'TypeFloat',      1, UNIX_TIMESTAMP()),
('data-types', 10, 'double',     'TypeDouble',     1, UNIX_TIMESTAMP()),
('data-types', 11, 'timestamp',  'TypeTimestamp',  1, UNIX_TIMESTAMP()),
('data-types', 12, 'data',       'TypeDate',       1, UNIX_TIMESTAMP()),
('data-types', 13, 'time',       'TypeTime',       1, UNIX_TIMESTAMP()),
('data-types', 14, 'datetime',   'TypeDatetime',   1, UNIX_TIMESTAMP()),
('data-types', 15, 'year',       'TypeYear',       1, UNIX_TIMESTAMP()),
('data-types', 16, 'char',       'TypeChar',       1, UNIX_TIMESTAMP()),
('data-types', 17, 'varchar',    'TypeVarchar',    1, UNIX_TIMESTAMP()),
('data-types', 18, 'json',       'TypeJSON',       1, UNIX_TIMESTAMP()),
('data-types', 19, 'enum',       'TypeEnum',       1, UNIX_TIMESTAMP()),
('data-types', 20, 'set',        'TypeSet',        1, UNIX_TIMESTAMP()),
('data-types', 21, 'binary',     'TypeBinary',     1, UNIX_TIMESTAMP()),
('data-types', 22, 'varbinary',  'TypeVarbinary',  1, UNIX_TIMESTAMP()),
('data-types', 23, 'tinyblob',   'TypeTinyBlob',   1, UNIX_TIMESTAMP()),
('data-types', 24, 'blob',       'TypeBlob',       1, UNIX_TIMESTAMP()),
('data-types', 25, 'mediumblob', 'TypeMediumBlob', 1, UNIX_TIMESTAMP()),
('data-types', 26, 'longblob',   'TypeLongBlob',   1, UNIX_TIMESTAMP()),
('data-types', 27, 'tinytext',   'TypeTinyText',   1, UNIX_TIMESTAMP()),
('data-types', 28, 'text',       'TypeText',       1, UNIX_TIMESTAMP()),
('data-types', 29, 'mediumtext', 'TypeMediumText', 1, UNIX_TIMESTAMP()),
('data-types', 30, 'longtext',   'TypeLongText',   1, UNIX_TIMESTAMP())
;


INSERT INTO `mm_glossaries`(catalog, iota, name, description, version, create_at) VALUES 
('storage-engines',  1, 'InnoDB',    'The most widely used storage engine with transaction support',                                1, UNIX_TIMESTAMP()),
('storage-engines',  2, 'MyISAM',    'Non-transactional storage engine with good performance and small data footprint',             1, UNIX_TIMESTAMP()),
('storage-engines',  3, 'CSV',       'Works with files stored in CSV (comma-separated-values) format',                              1, UNIX_TIMESTAMP()),
('storage-engines',  4, 'Memory',    'Storage engine stored in memory rather than on disk',                                         1, UNIX_TIMESTAMP()),
('storage-engines',  5, 'Blackhole', 'Storage engine that accepts data without storing it',                                         1, UNIX_TIMESTAMP()),
('storage-engines',  6, 'TokuDB',    'For use in high-performance and write-intensive environments',                                1, UNIX_TIMESTAMP()),
('storage-engines',  7, 'RocksDB',   'An LSM database with a great compression ratio that is optimized for flash storage',          1, UNIX_TIMESTAMP()),
('storage-engines',  8, 'Archive',   'Stores data in compressed (gzip) format',                                                     1, UNIX_TIMESTAMP()),
('storage-engines',  9, 'Aria',      'The Aria storage engine is compiled-in by default and is considered as an upgrade to MyISAM', 1, UNIX_TIMESTAMP()),
('storage-engines', 10, 'Cassandra', 'A storage engine interface to Cassandra',                                                     1, UNIX_TIMESTAMP()),
('storage-engines', 11, 'Federated', 'Allows you to access tables in other MariaDB or MySQL servers',                               1, UNIX_TIMESTAMP())
;


INSERT INTO `mm_glossaries`(catalog, iota, name, description, version, create_at) VALUES
('rules.group',  1, 'database-create',  '...', 1, UNIX_TIMESTAMP()),
('rules.group',  2, 'database-alter',   '...', 1, UNIX_TIMESTAMP()),
('rules.group',  3, 'database-drop',    '...', 1, UNIX_TIMESTAMP()),
('rules.group',  4, 'database-use',     '...', 1, UNIX_TIMESTAMP()),
('rules.group',  5, 'table-create',     '...', 1, UNIX_TIMESTAMP()),
('rules.group',  6, 'table-alter',      '...', 1, UNIX_TIMESTAMP()),
('rules.group',  7, 'table-drop',       '...', 1, UNIX_TIMESTAMP()),
('rules.group',  8, 'table-rename',     '...', 1, UNIX_TIMESTAMP()),
('rules.group',  9, 'table-truncate',   '...', 1, UNIX_TIMESTAMP()),
('rules.group', 10, 'table-lock',       '...', 1, UNIX_TIMESTAMP()),
('rules.group', 11, 'table-unlock',     '...', 1, UNIX_TIMESTAMP()),
('rules.group', 12, 'table-flush',      '...', 1, UNIX_TIMESTAMP()),
('rules.group', 13, 'process-list',     '...', 1, UNIX_TIMESTAMP()),
('rules.group', 14, 'process-kill',     '...', 1, UNIX_TIMESTAMP()),
('rules.group', 15, 'index-create',     '...', 1, UNIX_TIMESTAMP()),
('rules.group', 16, 'index-drop',       '...', 1, UNIX_TIMESTAMP()),
('rules.group', 17, 'index-alter',      '...', 1, UNIX_TIMESTAMP()),
('rules.group', 18, 'data-insert',      '...', 1, UNIX_TIMESTAMP()),
('rules.group', 19, 'data-update',      '...', 1, UNIX_TIMESTAMP()),
('rules.group', 20, 'data-delete',      '...', 1, UNIX_TIMESTAMP()),
('rules.group', 21, 'data-replace',     '...', 1, UNIX_TIMESTAMP()),
('rules.group', 22, 'data-select',      '...', 1, UNIX_TIMESTAMP()),
('rules.group', 23, 'view-create',      '...', 1, UNIX_TIMESTAMP()),
('rules.group', 24, 'view-alter',       '...', 1, UNIX_TIMESTAMP()),
('rules.group', 25, 'view-drop',        '...', 1, UNIX_TIMESTAMP()),
('rules.group', 26, 'event-create',     '...', 1, UNIX_TIMESTAMP()),
('rules.group', 27, 'event-alter',      '...', 1, UNIX_TIMESTAMP()),
('rules.group', 28, 'event-drop',       '...', 1, UNIX_TIMESTAMP()),
('rules.group', 29, 'procedure-create', '...', 1, UNIX_TIMESTAMP()),
('rules.group', 30, 'procedure-alter',  '...', 1, UNIX_TIMESTAMP()),
('rules.group', 31, 'procedure-drop',   '...', 1, UNIX_TIMESTAMP()),
('rules.group', 32, 'func-create',      '...', 1, UNIX_TIMESTAMP()),
('rules.group', 33, 'func-alter',       '...', 1, UNIX_TIMESTAMP()),
('rules.group', 34, 'func-drop',        '...', 1, UNIX_TIMESTAMP()),
('rules.group', 35, 'trigger-create',   '...', 1, UNIX_TIMESTAMP()),
('rules.group', 36, 'trigger-alter',    '...', 1, UNIX_TIMESTAMP()),
('rules.group', 37, 'trigger-drop',     '...', 1, UNIX_TIMESTAMP())
;


INSERT INTO `mm_glossaries`(catalog, iota, name, description, version, create_at) VALUES
('instances.status',  0, 'closed',  'The instance is closed for some reason', 1, UNIX_TIMESTAMP()), # 机器主动下线，可能是服务器调整等各种原因
('instances.status',  1, 'running',   'The instance is running', 1, UNIX_TIMESTAMP()),              # 正常服务中
('instances.status',  1, 'suspected',   'The instance is suspected', 1, UNIX_TIMESTAMP())           # 可能是连接账号密码等问题
;


INSERT INTO `mm_glossaries`(catalog, iota, name, description, version, create_at) VALUES
('users.status',  0, 'waiting-for-activation',  '...', 1, UNIX_TIMESTAMP()), # 等待激活
('users.status',  1, 'normal',   '...', 1, UNIX_TIMESTAMP()),                # 正常
('users.status',  2, 'closed',   '...', 1, UNIX_TIMESTAMP()),                # 主动关闭，可能是职位调整或离职等原因
;


INSERT INTO mm_glossaries (catalog, iota, name, description, version, create_at) VALUES
('charsets',  1, 'big5',     '', 1, UNIX_TIMESTAMP()),
('charsets',  2, 'dec8',     '', 1, UNIX_TIMESTAMP()),
('charsets',  3, 'cp850',    '', 1, UNIX_TIMESTAMP()),
('charsets',  4, 'hp8',      '', 1, UNIX_TIMESTAMP()),
('charsets',  5, 'koi8r',    '', 1, UNIX_TIMESTAMP()),
('charsets',  6, 'latin1',   '', 1, UNIX_TIMESTAMP()),
('charsets',  7, 'latin2',   '', 1, UNIX_TIMESTAMP()),
('charsets',  8, 'swe7',     '', 1, UNIX_TIMESTAMP()),
('charsets',  9, 'ascii',    '', 1, UNIX_TIMESTAMP()),
('charsets', 10, 'ujis',     '', 1, UNIX_TIMESTAMP()),
('charsets', 11, 'sjis',     '', 1, UNIX_TIMESTAMP()),
('charsets', 12, 'hebrew',   '', 1, UNIX_TIMESTAMP()),
('charsets', 13, 'tis620',   '', 1, UNIX_TIMESTAMP()),
('charsets', 14, 'euckr',    '', 1, UNIX_TIMESTAMP()),
('charsets', 15, 'koi8u',    '', 1, UNIX_TIMESTAMP()),
('charsets', 16, 'gb2312',   '', 1, UNIX_TIMESTAMP()),
('charsets', 17, 'greek',    '', 1, UNIX_TIMESTAMP()),
('charsets', 18, 'cp1250',   '', 1, UNIX_TIMESTAMP()),
('charsets', 19, 'gbk',      '', 1, UNIX_TIMESTAMP()),
('charsets', 20, 'latin5',   '', 1, UNIX_TIMESTAMP()),
('charsets', 21, 'armscii8', '', 1, UNIX_TIMESTAMP()),
('charsets', 22, 'utf8',     '', 1, UNIX_TIMESTAMP()),
('charsets', 23, 'ucs2',     '', 1, UNIX_TIMESTAMP()),
('charsets', 24, 'cp866',    '', 1, UNIX_TIMESTAMP()),
('charsets', 25, 'keybcs2',  '', 1, UNIX_TIMESTAMP()),
('charsets', 26, 'macce',    '', 1, UNIX_TIMESTAMP()),
('charsets', 27, 'macroman', '', 1, UNIX_TIMESTAMP()),
('charsets', 28, 'cp852',    '', 1, UNIX_TIMESTAMP()),
('charsets', 29, 'latin7',   '', 1, UNIX_TIMESTAMP()),
('charsets', 30, 'utf8mb4',  '', 1, UNIX_TIMESTAMP()),
('charsets', 31, 'cp1251',   '', 1, UNIX_TIMESTAMP()),
('charsets', 32, 'utf16',    '', 1, UNIX_TIMESTAMP()),
('charsets', 33, 'utf16le',  '', 1, UNIX_TIMESTAMP()),
('charsets', 34, 'cp1256',   '', 1, UNIX_TIMESTAMP()),
('charsets', 35, 'cp1257',   '', 1, UNIX_TIMESTAMP()),
('charsets', 36, 'utf32',    '', 1, UNIX_TIMESTAMP()),
('charsets', 37, 'binary',   '', 1, UNIX_TIMESTAMP()),
('charsets', 38, 'geostd8',  '', 1, UNIX_TIMESTAMP()),
('charsets', 39, 'cp932',    '', 1, UNIX_TIMESTAMP()),
('charsets', 40, 'eucjpms',  '', 1, UNIX_TIMESTAMP())
;


INSERT INTO mm_glossaries (catalog, iota, name, description, version, create_at) VALUES
('collations',   1, 'big5_chinese_ci',          '', 1, UNIX_TIMESTAMP()),
('collations',   2, 'latin2_czech_cs',          '', 1, UNIX_TIMESTAMP()),
('collations',   3, 'dec8_swedish_ci',          '', 1, UNIX_TIMESTAMP()),
('collations',   4, 'cp850_general_ci',         '', 1, UNIX_TIMESTAMP()),
('collations',   5, 'latin1_german1_ci',        '', 1, UNIX_TIMESTAMP()),
('collations',   6, 'hp8_english_ci',           '', 1, UNIX_TIMESTAMP()),
('collations',   7, 'koi8r_general_ci',         '', 1, UNIX_TIMESTAMP()),
('collations',   8, 'latin1_swedish_ci',        '', 1, UNIX_TIMESTAMP()),
('collations',   9, 'latin2_general_ci',        '', 1, UNIX_TIMESTAMP()),
('collations',  10, 'swe7_swedish_ci',          '', 1, UNIX_TIMESTAMP()),
('collations',  11, 'ascii_general_ci',         '', 1, UNIX_TIMESTAMP()),
('collations',  12, 'ujis_japanese_ci',         '', 1, UNIX_TIMESTAMP()),
('collations',  13, 'sjis_japanese_ci',         '', 1, UNIX_TIMESTAMP()),
('collations',  14, 'cp1251_bulgarian_ci',      '', 1, UNIX_TIMESTAMP()),
('collations',  15, 'latin1_danish_ci',         '', 1, UNIX_TIMESTAMP()),
('collations',  16, 'hebrew_general_ci',        '', 1, UNIX_TIMESTAMP()),
('collations',  18, 'tis620_thai_ci',           '', 1, UNIX_TIMESTAMP()),
('collations',  19, 'euckr_korean_ci',          '', 1, UNIX_TIMESTAMP()),
('collations',  20, 'latin7_estonian_cs',       '', 1, UNIX_TIMESTAMP()),
('collations',  21, 'latin2_hungarian_ci',      '', 1, UNIX_TIMESTAMP()),
('collations',  22, 'koi8u_general_ci',         '', 1, UNIX_TIMESTAMP()),
('collations',  23, 'cp1251_ukrainian_ci',      '', 1, UNIX_TIMESTAMP()),
('collations',  24, 'gb2312_chinese_ci',        '', 1, UNIX_TIMESTAMP()),
('collations',  25, 'greek_general_ci',         '', 1, UNIX_TIMESTAMP()),
('collations',  26, 'cp1250_general_ci',        '', 1, UNIX_TIMESTAMP()),
('collations',  27, 'latin2_croatian_ci',       '', 1, UNIX_TIMESTAMP()),
('collations',  28, 'gbk_chinese_ci',           '', 1, UNIX_TIMESTAMP()),
('collations',  29, 'cp1257_lithuanian_ci',     '', 1, UNIX_TIMESTAMP()),
('collations',  30, 'latin5_turkish_ci',        '', 1, UNIX_TIMESTAMP()),
('collations',  31, 'latin1_german2_ci',        '', 1, UNIX_TIMESTAMP()),
('collations',  32, 'armscii8_general_ci',      '', 1, UNIX_TIMESTAMP()),
('collations',  33, 'utf8_general_ci',          '', 1, UNIX_TIMESTAMP()),
('collations',  34, 'cp1250_czech_cs',          '', 1, UNIX_TIMESTAMP()),
('collations',  35, 'ucs2_general_ci',          '', 1, UNIX_TIMESTAMP()),
('collations',  36, 'cp866_general_ci',         '', 1, UNIX_TIMESTAMP()),
('collations',  37, 'keybcs2_general_ci',       '', 1, UNIX_TIMESTAMP()),
('collations',  38, 'macce_general_ci',         '', 1, UNIX_TIMESTAMP()),
('collations',  39, 'macroman_general_ci',      '', 1, UNIX_TIMESTAMP()),
('collations',  40, 'cp852_general_ci',         '', 1, UNIX_TIMESTAMP()),
('collations',  41, 'latin7_general_ci',        '', 1, UNIX_TIMESTAMP()),
('collations',  42, 'latin7_general_cs',        '', 1, UNIX_TIMESTAMP()),
('collations',  43, 'macce_bin',                '', 1, UNIX_TIMESTAMP()),
('collations',  44, 'cp1250_croatian_ci',       '', 1, UNIX_TIMESTAMP()),
('collations',  45, 'utf8mb4_general_ci',       '', 1, UNIX_TIMESTAMP()),
('collations',  46, 'utf8mb4_bin',              '', 1, UNIX_TIMESTAMP()),
('collations',  47, 'latin1_bin',               '', 1, UNIX_TIMESTAMP()),
('collations',  48, 'latin1_general_ci',        '', 1, UNIX_TIMESTAMP()),
('collations',  49, 'latin1_general_cs',        '', 1, UNIX_TIMESTAMP()),
('collations',  50, 'cp1251_bin',               '', 1, UNIX_TIMESTAMP()),
('collations',  51, 'cp1251_general_ci',        '', 1, UNIX_TIMESTAMP()),
('collations',  52, 'cp1251_general_cs',        '', 1, UNIX_TIMESTAMP()),
('collations',  53, 'macroman_bin',             '', 1, UNIX_TIMESTAMP()),
('collations',  54, 'utf16_general_ci',         '', 1, UNIX_TIMESTAMP()),
('collations',  55, 'utf16_bin',                '', 1, UNIX_TIMESTAMP()),
('collations',  56, 'utf16le_general_ci',       '', 1, UNIX_TIMESTAMP()),
('collations',  57, 'cp1256_general_ci',        '', 1, UNIX_TIMESTAMP()),
('collations',  58, 'cp1257_bin',               '', 1, UNIX_TIMESTAMP()),
('collations',  59, 'cp1257_general_ci',        '', 1, UNIX_TIMESTAMP()),
('collations',  60, 'utf32_general_ci',         '', 1, UNIX_TIMESTAMP()),
('collations',  61, 'utf32_bin',                '', 1, UNIX_TIMESTAMP()),
('collations',  62, 'utf16le_bin',              '', 1, UNIX_TIMESTAMP()),
('collations',  63, 'binary',                   '', 1, UNIX_TIMESTAMP()),
('collations',  64, 'armscii8_bin',             '', 1, UNIX_TIMESTAMP()),
('collations',  65, 'ascii_bin',                '', 1, UNIX_TIMESTAMP()),
('collations',  66, 'cp1250_bin',               '', 1, UNIX_TIMESTAMP()),
('collations',  67, 'cp1256_bin',               '', 1, UNIX_TIMESTAMP()),
('collations',  68, 'cp866_bin',                '', 1, UNIX_TIMESTAMP()),
('collations',  69, 'dec8_bin',                 '', 1, UNIX_TIMESTAMP()),
('collations',  70, 'greek_bin',                '', 1, UNIX_TIMESTAMP()),
('collations',  71, 'hebrew_bin',               '', 1, UNIX_TIMESTAMP()),
('collations',  72, 'hp8_bin',                  '', 1, UNIX_TIMESTAMP()),
('collations',  73, 'keybcs2_bin',              '', 1, UNIX_TIMESTAMP()),
('collations',  74, 'koi8r_bin',                '', 1, UNIX_TIMESTAMP()),
('collations',  75, 'koi8u_bin',                '', 1, UNIX_TIMESTAMP()),
('collations',  77, 'latin2_bin',               '', 1, UNIX_TIMESTAMP()),
('collations',  78, 'latin5_bin',               '', 1, UNIX_TIMESTAMP()),
('collations',  79, 'latin7_bin',               '', 1, UNIX_TIMESTAMP()),
('collations',  80, 'cp850_bin',                '', 1, UNIX_TIMESTAMP()),
('collations',  81, 'cp852_bin',                '', 1, UNIX_TIMESTAMP()),
('collations',  82, 'swe7_bin',                 '', 1, UNIX_TIMESTAMP()),
('collations',  83, 'utf8_bin',                 '', 1, UNIX_TIMESTAMP()),
('collations',  84, 'big5_bin',                 '', 1, UNIX_TIMESTAMP()),
('collations',  85, 'euckr_bin',                '', 1, UNIX_TIMESTAMP()),
('collations',  86, 'gb2312_bin',               '', 1, UNIX_TIMESTAMP()),
('collations',  87, 'gbk_bin',                  '', 1, UNIX_TIMESTAMP()),
('collations',  88, 'sjis_bin',                 '', 1, UNIX_TIMESTAMP()),
('collations',  89, 'tis620_bin',               '', 1, UNIX_TIMESTAMP()),
('collations',  90, 'ucs2_bin',                 '', 1, UNIX_TIMESTAMP()),
('collations',  91, 'ujis_bin',                 '', 1, UNIX_TIMESTAMP()),
('collations',  92, 'geostd8_general_ci',       '', 1, UNIX_TIMESTAMP()),
('collations',  93, 'geostd8_bin',              '', 1, UNIX_TIMESTAMP()),
('collations',  94, 'latin1_spanish_ci',        '', 1, UNIX_TIMESTAMP()),
('collations',  95, 'cp932_japanese_ci',        '', 1, UNIX_TIMESTAMP()),
('collations',  96, 'cp932_bin',                '', 1, UNIX_TIMESTAMP()),
('collations',  97, 'eucjpms_japanese_ci',      '', 1, UNIX_TIMESTAMP()),
('collations',  98, 'eucjpms_bin',              '', 1, UNIX_TIMESTAMP()),
('collations',  99, 'cp1250_polish_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 101, 'utf16_unicode_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 102, 'utf16_icelandic_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 103, 'utf16_latvian_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 104, 'utf16_romanian_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 105, 'utf16_slovenian_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 106, 'utf16_polish_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 107, 'utf16_estonian_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 108, 'utf16_spanish_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 109, 'utf16_swedish_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 110, 'utf16_turkish_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 111, 'utf16_czech_ci',           '', 1, UNIX_TIMESTAMP()),
('collations', 112, 'utf16_danish_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 113, 'utf16_lithuanian_ci',      '', 1, UNIX_TIMESTAMP()),
('collations', 114, 'utf16_slovak_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 115, 'utf16_spanish2_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 116, 'utf16_roman_ci',           '', 1, UNIX_TIMESTAMP()),
('collations', 117, 'utf16_persian_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 118, 'utf16_esperanto_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 119, 'utf16_hungarian_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 120, 'utf16_sinhala_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 121, 'utf16_german2_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 122, 'utf16_croatian_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 123, 'utf16_unicode_520_ci',     '', 1, UNIX_TIMESTAMP()),
('collations', 124, 'utf16_vietnamese_ci',      '', 1, UNIX_TIMESTAMP()),
('collations', 128, 'ucs2_unicode_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 129, 'ucs2_icelandic_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 130, 'ucs2_latvian_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 131, 'ucs2_romanian_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 132, 'ucs2_slovenian_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 133, 'ucs2_polish_ci',           '', 1, UNIX_TIMESTAMP()),
('collations', 134, 'ucs2_estonian_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 135, 'ucs2_spanish_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 136, 'ucs2_swedish_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 137, 'ucs2_turkish_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 138, 'ucs2_czech_ci',            '', 1, UNIX_TIMESTAMP()),
('collations', 139, 'ucs2_danish_ci',           '', 1, UNIX_TIMESTAMP()),
('collations', 140, 'ucs2_lithuanian_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 141, 'ucs2_slovak_ci',           '', 1, UNIX_TIMESTAMP()),
('collations', 142, 'ucs2_spanish2_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 143, 'ucs2_roman_ci',            '', 1, UNIX_TIMESTAMP()),
('collations', 144, 'ucs2_persian_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 145, 'ucs2_esperanto_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 146, 'ucs2_hungarian_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 147, 'ucs2_sinhala_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 148, 'ucs2_german2_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 149, 'ucs2_croatian_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 150, 'ucs2_unicode_520_ci',      '', 1, UNIX_TIMESTAMP()),
('collations', 151, 'ucs2_vietnamese_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 159, 'ucs2_general_mysql500_ci', '', 1, UNIX_TIMESTAMP()),
('collations', 160, 'utf32_unicode_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 161, 'utf32_icelandic_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 162, 'utf32_latvian_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 163, 'utf32_romanian_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 164, 'utf32_slovenian_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 165, 'utf32_polish_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 166, 'utf32_estonian_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 167, 'utf32_spanish_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 168, 'utf32_swedish_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 169, 'utf32_turkish_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 170, 'utf32_czech_ci',           '', 1, UNIX_TIMESTAMP()),
('collations', 171, 'utf32_danish_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 172, 'utf32_lithuanian_ci',      '', 1, UNIX_TIMESTAMP()),
('collations', 173, 'utf32_slovak_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 174, 'utf32_spanish2_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 175, 'utf32_roman_ci',           '', 1, UNIX_TIMESTAMP()),
('collations', 176, 'utf32_persian_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 177, 'utf32_esperanto_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 178, 'utf32_hungarian_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 179, 'utf32_sinhala_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 180, 'utf32_german2_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 181, 'utf32_croatian_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 182, 'utf32_unicode_520_ci',     '', 1, UNIX_TIMESTAMP()),
('collations', 183, 'utf32_vietnamese_ci',      '', 1, UNIX_TIMESTAMP()),
('collations', 192, 'utf8_unicode_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 193, 'utf8_icelandic_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 194, 'utf8_latvian_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 195, 'utf8_romanian_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 196, 'utf8_slovenian_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 197, 'utf8_polish_ci',           '', 1, UNIX_TIMESTAMP()),
('collations', 198, 'utf8_estonian_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 199, 'utf8_spanish_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 200, 'utf8_swedish_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 201, 'utf8_turkish_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 202, 'utf8_czech_ci',            '', 1, UNIX_TIMESTAMP()),
('collations', 203, 'utf8_danish_ci',           '', 1, UNIX_TIMESTAMP()),
('collations', 204, 'utf8_lithuanian_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 205, 'utf8_slovak_ci',           '', 1, UNIX_TIMESTAMP()),
('collations', 206, 'utf8_spanish2_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 207, 'utf8_roman_ci',            '', 1, UNIX_TIMESTAMP()),
('collations', 208, 'utf8_persian_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 209, 'utf8_esperanto_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 210, 'utf8_hungarian_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 211, 'utf8_sinhala_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 212, 'utf8_german2_ci',          '', 1, UNIX_TIMESTAMP()),
('collations', 213, 'utf8_croatian_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 214, 'utf8_unicode_520_ci',      '', 1, UNIX_TIMESTAMP()),
('collations', 215, 'utf8_vietnamese_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 223, 'utf8_general_mysql500_ci', '', 1, UNIX_TIMESTAMP()),
('collations', 224, 'utf8mb4_unicode_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 225, 'utf8mb4_icelandic_ci',     '', 1, UNIX_TIMESTAMP()),
('collations', 226, 'utf8mb4_latvian_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 227, 'utf8mb4_romanian_ci',      '', 1, UNIX_TIMESTAMP()),
('collations', 228, 'utf8mb4_slovenian_ci',     '', 1, UNIX_TIMESTAMP()),
('collations', 229, 'utf8mb4_polish_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 230, 'utf8mb4_estonian_ci',      '', 1, UNIX_TIMESTAMP()),
('collations', 231, 'utf8mb4_spanish_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 232, 'utf8mb4_swedish_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 233, 'utf8mb4_turkish_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 234, 'utf8mb4_czech_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 235, 'utf8mb4_danish_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 236, 'utf8mb4_lithuanian_ci',    '', 1, UNIX_TIMESTAMP()),
('collations', 237, 'utf8mb4_slovak_ci',        '', 1, UNIX_TIMESTAMP()),
('collations', 238, 'utf8mb4_spanish2_ci',      '', 1, UNIX_TIMESTAMP()),
('collations', 239, 'utf8mb4_roman_ci',         '', 1, UNIX_TIMESTAMP()),
('collations', 240, 'utf8mb4_persian_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 241, 'utf8mb4_esperanto_ci',     '', 1, UNIX_TIMESTAMP()),
('collations', 242, 'utf8mb4_hungarian_ci',     '', 1, UNIX_TIMESTAMP()),
('collations', 243, 'utf8mb4_sinhala_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 244, 'utf8mb4_german2_ci',       '', 1, UNIX_TIMESTAMP()),
('collations', 245, 'utf8mb4_croatian_ci',      '', 1, UNIX_TIMESTAMP()),
('collations', 246, 'utf8mb4_unicode_520_ci',   '', 1, UNIX_TIMESTAMP()),
('collations', 247, 'utf8mb4_vietnamese_ci',    '', 1, UNIX_TIMESTAMP())
;


INSERT INTO `mm_glossaries`(catalog, iota, name, description, version, create_at) VALUES
('tickets.status',  0, 'pending',   '...', 1, UNIX_TIMESTAMP()), # 待处理
('tickets.status',  1, 'validated', '...', 1, UNIX_TIMESTAMP()), # 待处理
('tickets.status',  2, 'closed',    '...', 1, UNIX_TIMESTAMP())  # 待处理
;


INSERT INTO `mm_glossaries`(catalog, iota, name, description, version, create_at) VALUES
('statements.type',  1, 'DDL', 'Data Definition Language, refers to the CREATE, ALTER and DROP statements',                                            1, UNIX_TIMESTAMP()),
('statements.type',  2, 'DML', 'Data Manipulation Language, refers to the INSERT, UPDATE and DELETE statements',                                       1, UNIX_TIMESTAMP()),
('statements.type',  3, 'DQL', 'Data Query Language, refers to the SELECT, SHOW and HELP statements',                                                  1, UNIX_TIMESTAMP()),
('statements.type',  3, 'DCL', 'Data Control Language, refers to the GRANT and REVOKE statements',                                                     1, UNIX_TIMESTAMP()),
('statements.type',  3, 'DTL', 'Data Transaction Language, refers to the START TRANSACTION, SAVEPOINT, COMMIT and ROLLBACK [TO SAVEPOINT] statements', 1, UNIX_TIMESTAMP())
;


INSERT INTO `mm_glossaries`(catalog, iota, name, description, version, create_at) VALUES
('relations.type',  1, '...', '...', 1, UNIX_TIMESTAMP())
;

