CREATE TABLE `rules`
(
	`rule_id`     INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name`        VARCHAR(50) NOT NULL,
	`description` TINYTEXT NOT NULL,
	`valid`       TINYINT UNSIGNED NOT NULL DEFAULT 1,
	`mandatory`   TINYINT UNSIGNED NOT NULL DEFAULT 1,
	PRIMARY KEY (`rule_id`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;
